- .github/ISSUE_TEMPLATE/01_bugReport.md
- .github/ISSUE_TEMPLATE/02_enhancementRequest.md
- .github/ISSUE_TEMPLATE/03_featureRequest.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- CONTRIBUTING.md
Adding missing open source community health files:
- issue templates for bug report, enhancement request and feature request
- pull request template
- contributing guidelines document
> Add missing open source community health files

- build.gradle
* nrich version: v1.1.1
Fixed URL for Nexus Staging Repository used by the Nexus Publish Plugin, as introduced in [PR 6](https://github.com/croz-ltd/nrich/pull/6).
Set correct URL.
> Fix Nexus Staging Repository URL for Publish Plugin

- .github/ISSUE_TEMPLATE/01_bugReport.md
- .github/ISSUE_TEMPLATE/02_enhancementRequest.md
- .github/ISSUE_TEMPLATE/03_featureRequest.md
1.1.1
* Module:
Project
Issue templates were wrongly formatted in previous PR and need to be fixed.
-  ~~I have checked my code with the project's static analysis tooling~~
> Fix issues templates that were wrongly formatted

- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/service/MessageSourceFieldErrorMessageResolverService.java
- nrich-notification-spring-boot-starter/src/main/java/net/croz/nrich/notification/starter/configuration/NrichNotificationAutoConfiguration.java
- nrich-notification/src/main/java/net/croz/nrich/notification/service/MessageSourceNotificationMessageResolverService.java
- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/data/service/RegistryDataService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/comparator/DisplayOrderComparator.java
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/comparator/RegistryGroupConfigurationComparator.java
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/comparator/RegistryPropertyComparator.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/model/RegistryDataConfigurationHolder.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/service/DefaultRegistryConfigurationResolverService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/controller/RegistryDataController.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/configuration/controller/RegistryConfigurationControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/service/DefaultRegistryDataServiceTest.java
- nrich-search-repository-api/src/main/java/net/croz/nrich/search/api/factory/SearchExecutorJpaRepositoryFactoryBean.java
- nrich-search-spring-boot-starter/src/main/java/net/croz/nrich/search/starter/configuration/NrichSearchAutoConfiguration.java
- nrich-search/src/main/java/net/croz/nrich/search/bean/MapSupportingDirectFieldAccessFallbackBeanWrapper.java
- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PathResolvingUtil.java
- nrich-security-csrf/src/main/java/net/croz/nrich/security/csrf/core/constants/AesCsrfTokenConstants.java
- nrich-security-csrf/src/main/java/net/croz/nrich/security/csrf/core/service/AesCsrfTokenManagerService.java
- nrich-security-csrf/src/main/java/net/croz/nrich/security/csrf/webmvc/interceptor/CsrfInterceptor.java
- nrich-security-csrf/src/test/java/net/croz/nrich/security/csrf/core/service/AesCsrfTokenManagerServiceTest.java
- nrich-security-csrf/src/test/java/net/croz/nrich/security/csrf/webflux/filter/CsrfWebFilterTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/validator/ValidFileResolvableValidatorTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/validator/ValidFileValidatorTest.java
- nrich-webmvc/src/main/java/net/croz/nrich/webmvc/advice/NotificationErrorHandlingRestControllerAdvice.java
- nrich-webmvc/src/test/java/net/croz/nrich/webmvc/advice/stub/NotificationErrorHandlingRestControllerAdviceTestController.java
1.1.1
* Module:
Project
Try to reduce number of sonar warnings, not all warnings are valid or can be solved but solve the ones that can be.
Fixed most of the issues, some issues have remained since currently I see no way of fixing them (TODO comments, wildcard types and too many arguments in constructor and methods).
https://github.com/croz-ltd/nrich/issues/18
- Refactoring
> Resolve sonar warnings

- README.md
- build.gradle
- nrich-bom/README.md
- nrich-bom/build.gradle
- settings.gradle
1.2.0
* Module:
Project
Adding nrich bom module to enable easier adding of nrich dependencies.
Added a nrich bom module, configured build and publish to include that module.
https://github.com/croz-ltd/nrich/issues/28
> Feature introduce bom

- nrich-search/src/main/java/net/croz/nrich/search/model/AttributeHolder.java
- nrich-search/src/main/java/net/croz/nrich/search/model/AttributeHolderWithPath.java
- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/main/java/net/croz/nrich/search/support/JpaEntityAttributeResolver.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PathResolvingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestDoubleNestedEntity.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntitySearchRequest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/JpaSearchRepositoryExecutorGeneratingUtil.java
1.2.1
* Module:
nrich-search
It would be good to support searching by any level of nested path by prefix.
Added support for searching by any level of nested path by prefix.
Added support for searching by any level of nested path by prefix.
https://github.com/croz-ltd/nrich/issues/49
> Feature support searching by any level of nested path

- settings.gradle
* nrich version:  v1.2.1
Renamed root gradle project from "nrichcode" to "nrich".
The root gradle project name was defined as "nrichcode" in settings.gradle. Renamed it to "nrich" as "nrichcode" is the old legacy name of the project.
#86 
- Refactoring
> Rename gradle rootProject to "nrich"

- gradle.properties
1.2.1
* Module:
Project
Upgrade Spring Boot to 2.6.6
Upgrade Spring Boot to 2.6.6
https://github.com/croz-ltd/nrich/issues/69
> Upgrade Spring Boot to 2.6.6

- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfiguration.java
- nrich-search-spring-boot-starter/src/main/java/net/croz/nrich/search/starter/configuration/NrichSearchAutoConfiguration.java
1.2.1
* Module:
nrich-registry-spring-boot-starter, nrich-search-spring-boot-starter
Reduced (where possible) Bean '...' of type [...] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) messages displayed on startup filtered beans injected in registry and search StringToEntityPropertyMapConverter bean to avoid including the same bean twice.
Reduced (where possible) Bean '...' of type [...] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) messages displayed on startup filtered beans injected in registry and search StringToEntityPropertyMapConverter bean to avoid including the same bean twice.
https://github.com/croz-ltd/nrich/issues/79
- Refactoring
- …
> Feature reduce number of info messages on startup

- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/properties/NrichRegistryProperties.java
- nrich-registry/README.md
- nrich-registry/src/test/java/net/croz/nrich/registry/RegistryTestConfiguration.java
- nrich-search-spring-boot-starter/src/main/java/net/croz/nrich/search/starter/properties/NrichSearchProperties.java
- nrich-search/README.md
- nrich-search/src/test/java/net/croz/nrich/search/SearchTestConfiguration.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToTypeConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/testutil/ConverterGeneratingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/JpaStringSearchExecutorTest.java
1.2.1
* Module:
nrich-search, nrich-registry
Sync date and date time format separators.
Sync date and date time format separators.
https://github.com/croz-ltd/nrich/issues/77
- Refactoring
> Feature sync date and date time format separator

- gradle.properties
* nrich version: v1.3.0
* Module: nrich-excel, nrich-excel-spring-boot-starter
Upgraded Apache POI library to version 5.2.2.
Upgraded Apache POI library to version 5.2.2.
#96 
> Update Apache POI library to latest stable version

- README.md
* nrich version: v1.3.0
Fixed broken GitHub pages Javadoc link in main README.
Fixed broken GitHub pages Javadoc link in main README.
Updated URL to https://croz-ltd.github.io/nrich .
#100 
> Fix Javadoc badge URL

- nrich-search/build.gradle
- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/main/java/net/croz/nrich/search/repository/JpaSearchExecutor.java
- nrich-search/src/main/java/net/croz/nrich/search/repository/JpaStringSearchExecutor.java
- nrich-search/src/main/java/net/croz/nrich/search/support/JpaQueryBuilder.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PathResolvingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/util/PathResolvingUtilTest.java
1.3.0
* Module:
nrich-search
Replaced count queries that were used to for exists methods with select 1, replaced subqueries id selection with select 1.
Replaced count queries that were used to for exists methods with select 1, replaced subqueries id selection with select 1.
- Refactoring
> Feature optimise exist queries

- README.md
1.3.0
* Module:
Project
Document minimum Java and Spring versions used by Nrich library.
Document minimum Java and Spring versions used by Nrich library.
https://github.com/croz-ltd/nrich/issues/53
- Docs change
> Document minimum Java and Spring versions used by Nrich library versions

- build.gradle
- nrich-search-repository-api/src/main/java/net/croz/nrich/search/api/repository/NaturalIdSearchExecutor.java
- nrich-search/README.md
- nrich-search/build.gradle
- nrich-search/src/main/java/net/croz/nrich/search/factory/SearchRepositoryJpaRepositoryFactory.java
- nrich-search/src/main/java/net/croz/nrich/search/repository/HibernateNaturalIdSearchExecutor.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/HibernateNaturalIdSearchExecutorTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntityWithNaturalId.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntityWithNaturalIdSearchRepository.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntityWithSimpleNaturalId.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntityWithSimpleNaturalIdSearchRepository.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/HibernateNaturalIdSearchExecutorGeneratingUtil.java
1.3.0
* Module:
nrich-search
Added support for searching by @NaturalId annotated properties.
Added support for searching by @NaturalId annotated properties.
https://github.com/croz-ltd/nrich/issues/107
> Feature add natural id search executor

- nrich-logging-spring-boot-starter/build.gradle
1.4.0
* Module:
nrich-logging-spring-boot-starter
Added description to nrich-spring-boot-starter-logging
Added description to nrich-spring-boot-starter-logging
- Docs change
> Add description for nrich-logging-spring-boot-starter

- README.md
1.4.0
* Module:
Project
Updated compatibility table to include newly released 1.4.0 version
Updated compatibility table to include newly released 1.4.0 version
- Docs change
> Update compatibility table to include version 1.4.x

- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/JpaSearchExecutorTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
1.4.1
* Module:
nrich-search
Skip empty collection values when building a query for searching.
Skip empty collection values when building a query for searching.
https://github.com/croz-ltd/nrich/issues/128
> Feature ignore empty collections when searching

- nrich-form-configuration-api/src/main/java/net/croz/nrich/formconfiguration/api/annotation/FormValidationConfiguration.java
- nrich-form-configuration-api/src/main/java/net/croz/nrich/formconfiguration/api/service/FormConfigurationAnnotationResolvingService.java
- nrich-form-configuration-spring-boot-starter/README.md
- nrich-form-configuration-spring-boot-starter/src/main/java/net/croz/nrich/formconfiguration/starter/configuration/NrichFormConfigurationAutoConfiguration.java
- nrich-form-configuration-spring-boot-starter/src/main/java/net/croz/nrich/formconfiguration/starter/properties/NrichFormConfigurationProperties.java
- nrich-form-configuration-spring-boot-starter/src/test/java/net/croz/nrich/formconfiguration/starter/configuration/NrichFormConfigurationAutoConfigurationTest.java
- nrich-form-configuration-spring-boot-starter/src/test/java/net/croz/nrich/formconfiguration/starter/configuration/stub/FormConfigurationAnnotatedTestRequest.java
- nrich-form-configuration-spring-boot-starter/src/test/java/net/croz/nrich/formconfiguration/starter/configuration/stub/FormConfigurationTestRequest.java
- nrich-form-configuration/README.md
- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/service/DefaultFormConfigurationAnnotationResolvingService.java
- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/service/MessageSourceFieldErrorMessageResolverService.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/FormConfigurationTestConfiguration.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/service/DefaultFormConfigurationAnnotationResolvingServiceTest.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/service/DefaultFormConfigurationServiceTest.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/stub/FormConfigurationAnnotatedTestRequest.java
1.4.1
* Module:
nrich-form-configuration-api, nrich-form-configuration, nrich-form-configuration-spring-boot-starter
Added support for form configuration registration through annotation (`@FormConfigurationHolder`)
Added support for form configuration registration through annotation (`@FormConfigurationHolder`)
https://github.com/croz-ltd/nrich/issues/124
> Feature form configuration annotation support

- nrich-notification-api/README.md
- nrich-notification-spring-boot-starter/README.md
- nrich-notification/README.md
1.4.1
* Module:
nrich-notification
Changed documentation for `nrich-notification` submodules so that it contains more examples and is easier to follow.
Documentation that was changed and the changes made:
- `nrich-notification-api` changed `overview`
- `nrich-notification-spring-boot-starter` reformatted and reworded documentation
- `nrich-notification` added examples, restructured the README.md so that it is easier to follow when reading and searching
- Docs change
- ~~I have checked my code with the project's static analysis tooling~~ (not required as I did not change any code)
- ~~I have formatted my code with the project's IDEA code-style configuration~~  (not required as I did not change any code)
- ~~I have checked my code for misspellings~~  (not required as I did …
> Notification page documentation update

- nrich-search/src/main/java/net/croz/nrich/search/model/AttributeHolder.java
- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntity.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntitySearchRequest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/JpaSearchRepositoryExecutorGeneratingUtil.java
1.4.1
* Module:
nrich-search
Added support for searching by @ElementCollection annotated properties.
Added support for searching by @ElementCollection annotated properties.
> Feature support searching by element collection

- nrich-search-api/README.md
- nrich-search-repository-api/README.md
- nrich-search-spring-boot-starter/README.md
- nrich-search/README.md
1.4.1
* Module:
nrich-search
Changed documentation for `nrich-search` modules so that it contains more examples and is easier to follow.
Documentation that was changed and the changes made:
- `nrich-search-api` -> changed overview
- `nrich-search-repository-api` -> changed overview
- `nrich-search-spring-boot-starter` -> reformatted and reworded documentation
- `nrich-search` -> added examples, explanations, restructured the README.md so that it is easier to follow when reading and searching
- Docs change
- ~~I have checked my code with the project's static analysis tooling~~ (not required as I did not change any code)
- ~~I have formatted my code with the project's IDEA code-style configuration~~  (not required as I did not change any code)
- ~~I have checked my code for …
> Search page documentation update

- nrich-form-configuration/README.md
- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/constants/FormConfigurationConstants.java
- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/service/MessageSourceFieldErrorMessageResolverService.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/service/MessageSourceFieldErrorMessageResolverServiceTest.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/testutil/FormConfigurationGeneratingUtil.java
- nrich-form-configuration/src/test/resources/messages.properties
1.4.3
* Module:
nrich-form-configuration
Added additional message code for resolving validation messages for form configuration.
Added additional message code for resolving validation messages for form configuration.
https://github.com/croz-ltd/nrich/issues/137
> Feature add additional message codes for form configuration

- README.md
1.4.4
* Module:
Project
Update README.md to include new Spring Boot version
Update README.md to include new Spring Boot version
- Docs change
- ~~All new and existing tests pass.~~
> Update README.md to include new Spring Boot version

- .github/codecov.yml
1.6.0
* Module:
project
Allow for tolerating of 1% coverage drop in pull requests. 
Allow for tolerating of 1% coverage drop in pull requests.
https://github.com/croz-ltd/nrich/issues/114
> Add some leniency to PR coverege checks

- README.md
1.6.0
* Module:
project
Update README with version 1.6
Update README with version 1.6
- Docs change
-  ~~I have checked my code with the project's static analysis tooling~~
> Update README with version 1.6

- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/service/DefaultRegistryDataServiceTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/RegistryTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/ValidationGroupOne.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
1.7.0
* Module:
nrich-registry
Add test for registry validation using groups.
Add test for registry validation using groups.
> Add test for registry validation when using groups

- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/core/model/RegistryConfiguration.java
- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/core/service/RegistryClassResolvingService.java
- nrich-registry-spring-boot-starter/README.md
- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfiguration.java
- nrich-registry-spring-boot-starter/src/test/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfigurationTest.java
- nrich-registry/README.md
- nrich-registry/src/main/java/net/croz/nrich/registry/core/constants/RegistryClassResolvingConstants.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/service/DefaultRegistryClassResolvingService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/customizer/RegistryDataFormConfigurationMappingCustomizer.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataRequestConversionService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/RegistryTestConfiguration.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/service/DefaultRegistryClassResolvingServiceTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/RegistryClassLoadingSecondTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/RegistryClassLoadingTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/entity/RegistryClassLoadingThirdTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/request/RegistryClassLoadingTestEntityCreateRequest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/request/RegistryClassLoadingTestEntityUpdateRequest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/stub/request/RegistryClassLoadingThirdTestEntityCreateRequest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/customizer/RegistryDataFormConfigurationMappingCustomizerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/service/DefaultRegistryDataRequestConversionServiceTest.java
1.7.1
* Module:
nrich-registry, nrich-registry-spring-boot-starter
Support resolving of registry classes for binding json data from additional packages. Allow for overriding of default behaviour by defining a bean implementing `RegistryClassResolvingService`. Also allow for defining of 
custom mapping through registry properties.
Support resolving of registry classes for binding json data from additional packages. Allow for overriding of default behaviour by defining a bean implementing `RegistryClassResolvingService`.  Also allow for defining of 
custom mapping through registry properties.
> Feature support additional packages and manual configuration for registry class resolving

- README.md
1.8.0
* Module:
Project
Update compatibility table to include version 1.8.x
Update compatibility table to include version 1.8.x
- Docs change
- ~~All new and existing tests pass.~~
>  Update compatibility table to include version 1.8.x

- nrich-jackson-spring-boot-starter/src/test/java/net/croz/nrich/jackson/starter/configuration/NrichJacksonAutoConfigurationTest.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
1.8.1
* Module:
nrich-jackson-spring-boot-starter, nrich-registry
General polishing.
General polishing.
- Refactoring
> Feature polishing

- nrich-notification/src/main/resources/nrich-notification-messages_hr.properties
* nrich version: 1.8.1
* Module: nrich-notification
Fixed typo in notification message
Fixed typo in notification message
- ~~I have added tests to cover my changes~~ (not needed as there are only changes to resource files)
> Fix typo in notification message

- README.md
1.8.1
* Module:
nrich
Update compatibility table to include version 2.0.0-RC1
Update compatibility table to include version 2.0.0-RC1
- Docs change
- ~~All new and existing tests pass.~~
> Update compatibility table to include version 2.0.0-RC1

- .github/workflows/build.yml
- nrich-search/src/main/java/net/croz/nrich/search/support/JpaQueryBuilder.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PathResolvingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/util/PathResolvingUtilTest.java
1.8.2
* Module:
nrich-search
When specifying a result class joins were added in jpa query selection for each property of the result class.
When specifying a result class joins were added in jpa query selection for each property of the result class.
https://github.com/croz-ltd/nrich/issues/169
-  ~~I have updated the documentation accordingly~~
> Skip joins on selections in query

- .github/workflows/build.yml
- .github/workflows/publish.yml
* nrich version: 
Removed unnecessary configuration for 2.x.x branch in the build and publish workflow.
Remove unnecessary configuration for 2.x.x branch in the build and publish workflow.
This was temporarily needed to enable publishing from 2.x.x branch which was used as release candidate for version 2.0.0.
> Remove unnecessary configuration for 2.x.x branch in the build and publish workflow

- README.md
* nrich version: 2.0.0
Update the compatibility matrix.
Update the compatibility matrix with information for the 2.0.0 version.
- Docs change
> Update the compatibility matrix

- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/enumdata/model/EnumResult.java
- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/enumdata/request/ListBulkRegistryEnumRequest.java
- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/enumdata/request/ListRegistryEnumRequest.java
- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/enumdata/service/RegistryEnumService.java
- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfiguration.java
- nrich-registry-spring-boot-starter/src/test/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfigurationTest.java
- nrich-registry/README.md
- nrich-registry/src/main/java/net/croz/nrich/registry/enumdata/controller/RegistryEnumController.java
- nrich-registry/src/main/java/net/croz/nrich/registry/enumdata/service/DefaultRegistryEnumService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/RegistryTestConfiguration.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/controller/RegistryEnumControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/service/DefaultRegistryEnumServiceTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/stub/RegistryTestEnum.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/stub/RegistryTestEnumWithAdditionalData.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/stub/RegistryTestEnumWithoutDescription.java
- nrich-registry/src/test/java/net/croz/nrich/registry/enumadata/testutil/RegistryEnumGeneratingUtil.java
- nrich-registry/src/test/resources/messages.properties
2.0.0
* Module:
nrich-registry, nrich-registry-spring-boot-starter
Add support for searching and resolving enum data
Add support for searching and resolving enum data
> Add support for searching and resolving enum data

- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/validator/SpelExpressionValidator.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/stub/SpelExpressionEnvirnomentTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/stub/SpelExpressionSystemPropertiesTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/validator/SpelExpressionValidatorTest.java
- nrich-validation/src/test/resources/application.properties
2.0.0
* Module:
nrich-validation
Enable environment and systemProperties access in SpelExpressionValidator
Enable environment and systemProperties access in SpelExpressionValidator
> Enable environment and systemProperties access in SpelExpressionValidator

- nrich-validation-api/src/main/java/net/croz/nrich/validation/api/constraint/DisableConstraints.java
- nrich-validation/README.md
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/BeanDescriptorAdapter.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/ConstraintFinderAdapter.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/DisableConstraintsAnnotationProcessor.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/HibernateValidatorAdapter.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/PathUtil.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/PropertyDescriptorAdapter.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/support/disableconstraints/ValidatorAdapter.java
- nrich-validation/src/main/resources/META-INF/services/jakarta.validation.spi.ValidationProvider
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/BeanDescriptorAdapterTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/ConstraintFinderAdapterTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/DisableConstraintsAnnotationProcessorTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/PathUtilTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/PropertyDescriptorAdapterTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/ValidatorAdapterTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/stub/DisableConstraintsAnnotationProcessorInvalidTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/stub/DisableConstraintsAnnotationProcessorTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/stub/DisableConstraintsParentTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/stub/DisableConstraintsPropertyAnnotationTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/stub/DisableConstraintsTypeAnnotationTestRequest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/support/disableconstraints/testutil/ConstraintDescriptorTestUtil.java
2.0.0
* Module:
nrich-validation, nrich-validation-api
Added support for disabling jakarta constraints.
Added support for disabling jakarta constraints.
> Add support for disabling constraints

- gradle.properties
2.0.0
* Module:
project
Upgrade Spring Boot to 3.1.5
Upgrade Spring Boot to 3.1.5
> Upgrade Spring Boot to 3.1.5

- nrich-validation-api/src/main/java/net/croz/nrich/validation/api/constraint/DisableConstraints.java
2.1.0
* Module:
nrich-validation-api
Add missing TYPE to @DisableConstraints annotation @Target
Add missing TYPE to @DisableConstraints annotation @Target
> Add missing TYPE to @DisableConstraints annotation @Target

- nrich-search/README.md
- nrich-search/build.gradle
- nrich-search/src/main/java/net/croz/nrich/search/util/GroovyUtil.java
- nrich-search/src/main/java/net/croz/nrich/search/util/ProjectionListResolverUtil.java
- nrich-search/src/test/groovy/net/croz/nrich/search/util/GroovyUtilTest.groovy
- nrich-search/src/test/groovy/net/croz/nrich/search/util/ProjectionListResolverUtilWithGroovyClosureTest.groovy
- nrich-search/src/test/groovy/net/croz/nrich/search/util/stub/ProjectionListResolverUtilWithGroovyClosureTestEntity.groovy
- nrich-search/src/test/groovy/net/croz/nrich/search/util/stub/ProjectionListResolverUtilWithGroovyClosureWithExceptionTestEntity.groovy
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/util/GroovyUtil.java
- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/validator/BaseNullableCheckValidator.java
* nrich version: 2.1.1
* Module: nrich-search
Support usage of Groovy closure in `@Projection` annotation
Condition for the  `@Projection` annotation can now be expressed with Groovy closure.
> Support usage of Groovy closure in @Projection annotation

- nrich-excel/src/main/java/net/croz/nrich/excel/util/TypeDataFormatUtil.java
- nrich-excel/src/test/java/net/croz/nrich/excel/converter/DefaultCellValueConverterTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/util/TypeDataFormatUtilTest.java
2.1.1
* Module:
nrich-excel
Add support for java.sql.Date and java.sql.Timestamp formatting when writing to excel
Add support for java.sql.Date and java.sql.Timestamp formatting when writing to excel
> Support java.sql.Date and java.sql.Timestamp when writing to excel

- nrich-registry/src/main/java/net/croz/nrich/registry/core/support/ManagedTypeWrapper.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/service/DefaultRegistryDataServiceTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/RegistryTestGroupType.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
2.1.1
* Module:
nrich-registry
Fix issue when loading associations for EmbeddedId, the assocation path was not calculated correctly
Fix issue when loading associations for EmbeddedId, the assocation path was not calculated correctly
> Fix loading associations for EmbeddedId

- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/model/Notification.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/model/ValidationFailureNotification.java
- nrich-notification/src/test/java/net/croz/nrich/notification/service/WebMvcNotificationResponseServiceTest.java
2.2.1
* Module:
nrich-notification
Add validation failure flag to notifications to make it easier to deterime notification type
Add validation failure flag to notifications to make it easier to deterime notification type
> Add validation failure flag to notifications

- nrich-encrypt-api/src/main/java/net/croz/nrich/encrypt/api/model/EncryptionContext.java
- nrich-encrypt/src/main/java/net/croz/nrich/encrypt/aspect/BaseEncryptDataAdvice.java
- nrich-encrypt/src/main/java/net/croz/nrich/encrypt/aspect/EncryptDataAspect.java
- nrich-encrypt/src/main/java/net/croz/nrich/encrypt/aspect/EncryptMethodInterceptor.java
2.3.0
* Module:
nrich-encrypt
Added current username to EncryptionContext
Added current username to EncryptionContext
> Added current username to EncryptionContext

- nrich-core-api/src/main/java/net/croz/nrich/core/api/exception/DefaultExceptionWithArguments.java
- nrich-webmvc/src/main/java/net/croz/nrich/webmvc/advice/NotificationErrorHandlingRestControllerAdvice.java
2.3.1
* Module:
nrich-core-api, nrich-webmvc
Change modifiers to protected to enable easier overriding
Change modifiers to protected to enable easier overriding
> Change modifiers to protected to enable easier overriding

- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/request/CreateExcelReportRequest.java
- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/request/CreateReportGeneratorRequest.java
- nrich-excel/README.md
- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGenerator.java
- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorFactory.java
- nrich-excel/src/main/java/net/croz/nrich/excel/service/DefaultExcelReportService.java
- nrich-excel/src/test/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/testutil/ExcelReportRequestGeneratingUtil.java
2.4.1.
* Module:
nrich-excel
Add support for autosizing excel columns
Add support for autosizing excel columns
> Add support for autosizing excel columns

- nrich-validation/src/main/resources/nrich-validation-messages.properties
- nrich-validation/src/main/resources/nrich-validation-messages_hr.properties
2.5.0
* Module:
nrich-validation
Add missing message for LastTimestampInDay constraint
Add missing message for LastTimestampInDay constraint
> Add missing message for LastTimestampInDay constraint

- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGenerator.java
2.5.2
* Module:
nrich-excel
Add quotes to strings when writing to excel
Add quotes to strings when writing to excel to avoid code being evaluated as a formula
- Docs change
- Refactoring
> Add quotes to strings when writing to excel

- nrich-encrypt/src/main/java/net/croz/nrich/encrypt/service/DefaultDataEncryptService.java
- nrich-encrypt/src/test/java/net/croz/nrich/encrypt/service/DefaultDataEncryptServiceTest.java
2.6.0
* Module:
nrich-encrypt
Don't log warn message when data for encrypt/decrypt is null
Don't log warn message when data for encrypt/decrypt is null
> Don't log warn message when data for encrypt/decrypt is null

- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/data/request/ListRegistryRequest.java
2.6.0
* Module:
nrich-registry-api
Change max page size on list registry request to 5000
> Change max page size on list registry request to 5000

- gradle.properties
2.6.1
* Module:
project
Upgraded dependencies
Upgraded dependencies
> Feature upgrade dependencies

- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/RegistryTestEntityUpdateRequest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
2.8.0
* Module:
nrich-registry
Fix updating association values. 
Fix updating association values. ModelMapper directly changes the id which causes exception:  org.springframework.orm.jpa.JpaSystemException: identifier of an instance of ... was changed from .. to ..
> Fix updating association values in registry module

- nrich-search/src/main/java/net/croz/nrich/search/util/ProjectionListResolverUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/util/ProjectionListResolverUtilTest.java
- nrich-search/src/test/java/net/croz/nrich/search/util/stub/ProjectionListResolverUtilTestEntityWithSuperclass.java
2.10
* Module:
nrich-search
Add support for resolving projection properties from superclasses of projection class.
Add support for resolving projection properties from superclasses of projection class.
- ~~ My change requires a change to the documentation~~
> Add support for resolving projection properties from superclass

- build.gradle
- gradle.properties
2.10.0
* Module:
project
Update publishing plugin and configuration
Update publishing plugin and configuration since OSSRH has reached the end of life. 
> Update publishing plugin and configuration
