croz-ltd/nrich

- .github/workflows/publish.yml
- build.gradle
- gradle.properties
* nrich version: v1.1.0
Implemented the [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin#gradle-nexus-publish-plugin) to completely automate the publish and release process to Maven Central. Automatic closing and releasing of "Nexus Staging Repositories" was not possible without this plugin.
- added plugin to the project and configured it
- updated the publish GH action to use new Gradle tasks provided by the plugin
> Automate maven central release process

- .github/workflows/publish.yml
- build.gradle
* nrich version: v1.1.0
As specified in the [Nexus Publish Plugin documentation](https://github.com/gradle-nexus/publish-plugin#behind-the-scenes) it's recommended to manually fetch the Nexus Staging Profile ID and explicitly configure it for the plugin, in order to enhance performance, and reduce execution time by several seconds, by avoiding 1 GET call to retrieve the ID.
- explicitly set fetched Staging Profile ID for plugin
- set GH secret and pass as env variable to relevant GH action
> Explicitly set Nexus Staging Profile ID

- .github/pull_request_template.md
* nrich version: v1.1.1
Updated PR template and instructions.
Replaced checkboxes with points in "Types of changes" and polished instructions, in order to have a cleaner process in regards to the "n of m tasks" GitHub PR display feature.
-  Enhancement (non-breaking change which enhances existing functionality)
- ~~My change requires a change to the documentation~~  (out of scope, just a PR template update)
- ~~I have updated the documentation accordingly~~  (out of scope, just a PR template update)
- ~~I have added tests to cover my changes~~ (out of scope, just a PR template update)
> Refactor checkboxes and instructions in Pull Request template

- .github/workflows/build.yml
- .github/workflows/publish.yml
- README.md
- build.gradle
- gradle.properties
* nrich version: 1.2.0
* Module: Project
Introduced aggregated coverage reports and codecov integration.
- implemented the `org.kordamp.gradle.jacoco` [plugin](https://plugins.gradle.org/plugin/org.kordamp.gradle.jacoco) for aggregated test coverage reports
- added integration with [codecov](https://app.codecov.io/gh/croz-ltd/nrich)
- added codecov GitHub badge
#25 
> Codecov report

- nrich-form-configuration-spring-boot-starter/src/main/java/net/croz/nrich/formconfiguration/starter/configuration/NrichFormConfigurationAutoConfiguration.java
- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfiguration.java
- nrich-security-csrf-spring-boot-starter/src/main/java/net/croz/nrich/security/csrf/configuration/NrichCsrfAutoConfiguration.java
- nrich-webmvc-spring-boot-starter/src/main/java/net/croz/nrich/webmvc/starter/configuration/NrichWebMvcAutoConfiguration.java
1.2.1
* Module:
Project
Some *AutoConfiguration classes are missing @ConditionalOnMissingBean annotations on some beans. Add where missing and appropriate.
Added @ConditionalOnMissingBean on beans where it was missing, add servlet restriction to registry controllers @ConditionalOnWebApplication annotation.
Added @ConditionalOnMissingBean on beans where it was missing, add servlet restriction to registry controllers @ConditionalOnWebApplication annotation.
https://github.com/croz-ltd/nrich/issues/34
> Add missing conditional on bean

- nrich-form-configuration/build.gradle
- nrich-form-configuration/src/main/java/net/croz/nrich/formconfiguration/controller/FormConfigurationController.java
- nrich-form-configuration/src/test/java/net/croz/nrich/formconfiguration/controller/FormConfigurationControllerTest.java
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/controller/RegistryConfigurationController.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/controller/RegistryDataController.java
- nrich-registry/src/main/java/net/croz/nrich/registry/history/controller/RegistryHistoryController.java
- nrich-registry/src/test/java/net/croz/nrich/registry/configuration/controller/RegistryConfigurationControllerEndpointTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerEndpointTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/history/controller/RegistryHistoryControllerEndpointTest.java
- nrich-registry/src/test/resources/application-test.yml
- nrich-security-csrf-spring-boot-starter/src/main/java/net/croz/nrich/security/csrf/configuration/NrichCsrfAutoConfiguration.java
- nrich-security-csrf/src/main/java/net/croz/nrich/security/csrf/core/controller/CsrfPingController.java
- nrich-security-csrf/src/test/java/net/croz/nrich/security/csrf/core/controller/CsrfPingControllerTest.java
1.2.1
* Module:
nrich-form-configuration, nrich-registry, nrich-security-csrf
It would be useful to allow customising path (RequestMapping) in all controllers.
Add support for customising path, changed the previous implementation in nrich-registry to allow for specifying full path.
Add support for customising path, changed the previous implementation in nrich-registry to allow for specifying full path.
https://github.com/croz-ltd/nrich/issues/38
- ~~I have updated the documentation accordingly~~ (documentation is not yet merged so currently it is not done)
> Feature support customising path in controllers

- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/generator/ExcelReportGenerator.java
- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/request/CreateExcelReportRequest.java
- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/request/CreateReportGeneratorRequest.java
- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/service/ExcelReportService.java
- nrich-excel/README.md
- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGenerator.java
- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorFactory.java
- nrich-excel/src/main/java/net/croz/nrich/excel/service/DefaultExcelReportService.java
- nrich-excel/src/test/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorFactoryTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/service/DefaultExcelReportServiceTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/testutil/ExcelReportRequestGeneratingUtil.java
- nrich-excel/src/test/java/net/croz/nrich/excel/testutil/PoiDataResolverUtil.java
* Module:
nrich-excel
Changes nrich-excel API to use OutputStream instead of File.
Changed nrich-excel API to accept OutputStream, simplified tests to use ByteArrayOutputStream (thus avoiding the need for creating temporary files).
Changed nrich-excel API to accept OutputStream, simplified tests to use ByteArrayOutputStream (thus avoiding the need for creating temporary files)
https://github.com/croz-ltd/nrich/issues/44
> Feature use output stream instead of file in excel module

- nrich-excel-api/src/main/java/net/croz/nrich/excel/api/request/CreateExcelReportRequest.java
- nrich-excel/README.md
- nrich-excel/src/test/java/net/croz/nrich/excel/service/DefaultExcelReportServiceTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/testutil/ExcelReportRequestGeneratingUtil.java
1.2.1
* Module:
nrich-excel
It would be good for users to be able to just specify flat data for excel without need for MultiRowDataProvider.
Add static methods for creating builders for CreateExcelReportRequest, one for flat data and another for MultiRowDataProvider.
Add static methods for creating builders for CreateExcelReportRequest, one for flat data and another for MultiRowDataProvider.
https://github.com/croz-ltd/nrich/issues/30
> Feature easier initialisation of flat data for excel report

- nrich-validation/src/main/java/net/croz/nrich/validation/constraint/validator/BaseValidFileValidator.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/validator/ValidFileResolvableValidatorTest.java
- nrich-validation/src/test/java/net/croz/nrich/validation/constraint/validator/ValidFileValidatorTest.java
1.2.1
* Module:
nrich-validation
In MultipartFile validation through ValidFile and ValidFileResolvable constraints instead of file name parameter name was used for validation, changed it to use original file name.
In MultipartFile validation through ValidFile and ValidFileResolvable constraints instead of file name parameter name was used for validation, changed it to use original file name.
> Fix issue with using the parameter name instead of filename

- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/response/NotificationDataResponse.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/response/NotificationResponse.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/service/BaseNotificationResponseService.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/service/NotificationResponseService.java
- nrich-notification-spring-boot-starter/src/main/java/net/croz/nrich/notification/starter/configuration/NrichNotificationAutoConfiguration.java
- nrich-notification-spring-boot-starter/src/test/java/net/croz/nrich/notification/starter/NrichNotificationAutoConfigurationTest.java
- nrich-notification/README.md
- nrich-notification/src/main/java/net/croz/nrich/notification/service/WebMvcNotificationResponseService.java
- nrich-notification/src/test/java/net/croz/nrich/notification/service/WebMvcNotificationResponseServiceTest.java
- nrich-webmvc-spring-boot-starter/src/main/java/net/croz/nrich/webmvc/starter/configuration/NrichWebMvcAutoConfiguration.java
- nrich-webmvc-spring-boot-starter/src/test/java/net/croz/nrich/webmvc/starter/configuration/stub/NotificationResponseTestService.java
- nrich-webmvc/README.md
- nrich-webmvc/src/main/java/net/croz/nrich/webmvc/advice/NotificationErrorHandlingRestControllerAdvice.java
- nrich-webmvc/src/test/java/net/croz/nrich/webmvc/WebmvcTestConfiguration.java
1.2.1
* Module:
nrich-notification, nrich-webmvc, nrich-logging
Added a separate class to represent a response notification without data, renamed existing class to end with Response suffix, renamed existing and added an additional interface in NotificationResolverService hierarchy that makes the usage easier.
Added a separate class to represent a response notification without data, renamed existing class to end with Response suffix, renamed existing and added an additional interface in NotificationResolverService hierarchy that makes the usage easier.
https://github.com/croz-ltd/nrich/issues/68
-  ~~I have added tests to cover my changes~~
> Feature improve notification service generics

- nrich-registry/build.gradle
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/constants/RegistryCoreConstants.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/constants/RegistryQueryConstants.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/service/DefaultRegistryConfigurationResolverService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/service/EntityManagerRegistryEntityFinderService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationServiceTest.java
1.2.1
* Module:
nrich-registry
Changed default display values for formLabel and columnHeader now they use capitalised and space separated attribute name i.e. (carId will be Car id) so the need for overriding of display values can be reduced.
Changed default display values for formLabel and columnHeader now they use capitalised and space separated attribute name i.e. (carId will be Car id) so the need for overriding of display values can be reduced.
https://github.com/croz-ltd/nrich/issues/72
> Feature change resolving of form and column display values

- nrich-search/src/main/java/net/croz/nrich/search/converter/DefaultStringToTypeConverter.java
- nrich-search/src/test/java/net/croz/nrich/search/SearchTestConfiguration.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToTypeConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/testutil/ConverterGeneratingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/JpaStringSearchExecutorTest.java
1.2.1
* Module:
nrich-search
Parsing of Instant, OffsetDateTime, OffsetTime and ZonedDateTime was failing since zone was absent in DateFormatter, added system zone to DateFormatter and synced date and date time formats in tests.
Parsing of Instant, OffsetDateTime, OffsetTime and ZonedDateTime was failing since zone was absent in DateFormatter, added system zone to DateFormatter and synced date and date time formats in tests.
https://github.com/croz-ltd/nrich/issues/76
> Fix parsing of dates

- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
- nrich-search-api/src/main/java/net/croz/nrich/search/api/converter/StringToEntityPropertyMapConverter.java
- nrich-search/src/main/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverter.java
- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/main/java/net/croz/nrich/search/repository/JpaStringSearchExecutor.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PropertyNameUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/JpaStringSearchExecutorTest.java
1.2.1
* Module:
nrich-registry, nrich-search
Added support for range queries in JpaStringSearchExecutor (i.e. dateFrom, dateTo etc)
Added support for range queries in JpaStringSearchExecutor (i.e. dateFrom, dateTo etc)
https://github.com/croz-ltd/nrich/issues/81
> Feature support range queries in string search

- .github/workflows/build.yml
- README.md
- build.gradle
- gradle.properties
1.3.0
* Module:
Project
Added gradle plugin and github workflow for generating and deploying javadoc to github pages.
Added gradle plugin and github workflow for generating and deploying javadoc to github pages.
https://github.com/croz-ltd/nrich/issues/57
> Feature deploy javadoc to GitHub pages

- nrich-logging-spring-boot-starter/README.MD
- nrich-logging-spring-boot-starter/build.gradle
- nrich-logging-spring-boot-starter/src/main/java/net/croz/nrich/logging/starter/configuration/NrichLoggingAutoConfiguration.java
- nrich-logging-spring-boot-starter/src/main/resources/META-INF/spring.factories
- nrich-logging-spring-boot-starter/src/test/java/net/croz/nrich/logging/starter/configuration/NrichLoggingAutoConfigurationTest.java
- nrich-webmvc-spring-boot-starter/build.gradle
- nrich-webmvc-spring-boot-starter/src/main/java/net/croz/nrich/webmvc/starter/configuration/NrichWebMvcAutoConfiguration.java
- nrich-webmvc-spring-boot-starter/src/test/java/net/croz/nrich/webmvc/starter/configuration/NrichWebMvcAutoConfigurationTest.java
- settings.gradle
1.3.0
* Module:
nrich-logging
Added Spring Boot starter module for nrich-logging, changed nrich-webmvc-spring-boot-starter dependencies to use that starter instead of manually creating LoggingService bean.
Added Spring Boot starter module for nrich-logging, changed nrich-webmvc-spring-boot-starter dependencies to use that starter instead of manually creating LoggingService bean.
https://github.com/croz-ltd/nrich/issues/32
> Feature add logging spring boot starter

- nrich-encrypt/src/main/java/net/croz/nrich/encrypt/service/DefaultDataEncryptService.java
- nrich-encrypt/src/test/java/net/croz/nrich/encrypt/service/DefaultDataEncryptServiceTest.java
- nrich-encrypt/src/test/java/net/croz/nrich/encrypt/service/stub/DataEncryptionServiceArrayTestObject.java
- nrich-encrypt/src/test/java/net/croz/nrich/encrypt/service/stub/DataEncryptionServiceTestObject.java
1.3.0
* Module:
nrich-encrypt
Added support for encryption/decryption of arrays or objects, arrays of strings and collections of strings. Limited allowed collection types to Set and List and fixed issue with Sets not being created correctly.
Added support for encryption/decryption of arrays or objects, arrays of strings and collections of strings. Limited allowed collection types to Set and List and fixed issue with Sets not being created correctly.
> Feature encryption improvements

- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/model/Notification.java
- nrich-webmvc-spring-boot-starter/build.gradle
- nrich-webmvc/build.gradle
- nrich-webmvc/src/test/java/net/croz/nrich/webmvc/advice/NotificationErrorHandlingRestControllerAdviceTest.java
1.4.0
* Module:
nrich-notification-api, nrich-webmvc,  nrich-webmvc-spring-boot-starter
Added notification timestamp to allow frontend display and easier handling (can be used as key when using React as frontend)
Added notification timestamp to allow frontend display and easier handling (can be used as key when using React as frontend)
> Add Notification timestamp to allow frontend display and easier handling

- nrich-search-repository-api/src/main/java/net/croz/nrich/search/api/factory/SearchExecutorJpaRepositoryFactoryBean.java
- nrich-search/src/test/java/net/croz/nrich/search/factory/SearchExecutorJpaRepositoryFactoryBeanIntegrationTest.java
- nrich-search/src/test/java/net/croz/nrich/search/factory/stub/SearchGetBeanConfiguration.java
1.4.0
* Module:
nrich-search
Refactored `SearchExecutorJpaRepositoryFactoryBean` initialization by moving constructor dependency resolving to `afterPropertiesSet` method.
Refactored `SearchExecutorJpaRepositoryFactoryBean` initialization by moving constructor dependency resolving to `afterPropertiesSet` method since the former fails when there are `getBean` calls before initialization is complete.
https://github.com/croz-ltd/nrich/issues/117
> Refactor SearchExecutorJpaRepositoryFactoryBean initialization

- nrich-registry/src/main/java/net/croz/nrich/registry/data/constant/RegistryDataConstants.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/customizer/RegistryDataFormConfigurationMappingCustomizer.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataRequestConversionService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/customizer/RegistryDataFormConfigurationMappingCustomizerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/model/RegistryCustomizerTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/request/RegistryCustomizerTestEntityCreateRequest.java
1.4.0
* Module:
nrich-registry
Added support for resolving of custom registry validation classes from request package.
Added support for resolving of custom registry validation classes from request package.
> Feature support loading requests from request package

- README.md
1.4.1
* Module:
nrich
Changed module's short descriptions and linked each header to correct module's README.md.
Reformatted, changed or reworded short descriptions of every module except `nrich-validation`. Linked every header to correct module README.md for easier navigation in documentation.
- Docs change
- ~~I have checked my code with the project's static analysis tooling~~ (not required as I did not change any code)
- ~~I have formatted my code with the project's IDEA code-style configuration~~  (not required as I did not change any code)
- ~~I have checked my code for misspellings~~  (not required as I did not change any code)
- ~~My change requires a change to the documentation~~  (not required as I did not change any code)
- ~~I have added tests to cover my …
> Main page documentation update

- nrich-form-configuration-api/README.md
- nrich-form-configuration-spring-boot-starter/README.md
- nrich-form-configuration/README.md
1.4.1
* Module:
nrich-form-configuration
Changed documentation for `nrich-form-configuration` modules so that it contains more examples and is easier to follow.
Documentation that was changed and the changes made:
- `nrich-form-configuration-api` -> changed overview
- `nrich-form-configuration-spring-boot-starter` -> reformatted and reworded documentation, added missing information
- `nrich-form-configuration` -> added examples, explanations, restructured the README.md so that it is easier to follow when reading and searching, added missing information
- Docs change
- ~~I have checked my code with the project's static analysis tooling~~ (not required as I did not change any code)
- ~~I have formatted my code with the project's IDEA code-style configuration~~  (not …
> Form configuration page documentation update

- build.gradle
- nrich-form-configuration-spring-boot-starter/src/main/java/net/croz/nrich/formconfiguration/starter/configuration/NrichFormConfigurationAutoConfiguration.java
1.4.1
* Module:
project
Make required changes to enable easier native image running.
Add parameters to compile java task to be able to use @ConfigurationProperties classes, use Validator interface instead of an implementation.
- Docs change
- Refactoring
> Feature improvements for native image run

- nrich-search-api/src/main/java/net/croz/nrich/search/api/model/property/SearchPropertyJoin.java
- nrich-search/src/main/java/net/croz/nrich/search/support/JpaQueryBuilder.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/stub/TestEntityWithCustomId.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/JpaSearchRepositoryExecutorGeneratingUtil.java
1.4.2
* Module:
nrich-search
Currently, only joining by a property named `id` is supported when using a subquery. We are adding support for joining by any property annotated with `@Id` annotation.
Currently, only joining by a property named `id` is supported when using a subquery. There are cases when we have a property with a different name representing the identity column. Because of that, we are adding support for joining by any property annotated with `@Id` annotation.
> Feature support join by custom id name

- nrich-registry-spring-boot-starter/README.md
- nrich-registry-spring-boot-starter/src/main/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfiguration.java
- nrich-registry-spring-boot-starter/src/test/java/net/croz/nrich/registry/starter/configuration/NrichRegistryAutoConfigurationTest.java
1.7.0
* Module:
nrich-registry-spring-boot-starter
Added support for overriding registry configuration by defining a bean of type `RegistryOverrideConfigurationHolder`.
Added support for overriding registry configuration by defining a bean of type `RegistryOverrideConfigurationHolder`.
> Enable easier registration of search overrides in registry module

- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/stub/RegistryTestEntityUpdateRequest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
1.8.0
* Module:
nrich-registry
Simplify resetting of id property on entity data in nrich-registry update method and fix IllegalArgumentException when jackson doesn't have DeserializationFeature.USE_LONG_FOR_INTS enabled
Simplify resetting of id property on entity data in nrich-registry update method and fix IllegalArgumentException when jackson doesn't have DeserializationFeature.USE_LONG_FOR_INTS enabled
- ~~My change requires a change to the documentation~`
> Fix IllegalArgumentException when Jackson doesn't have DeserializationFeature.USE_LONG_FOR_INTS enabled

- nrich-logging/src/main/java/net/croz/nrich/logging/service/Slf4jLoggingService.java
2.0.0
* Module:
nrich-logging
Relax access modifiers for Slf4jLoggingService to make it possible for clients to override methods
Relax access modifiers for Slf4jLoggingService to make it possible for clients to override methods
- ~~My change requires a change to the documentation~`
-  ~~I have added tests to cover my changes~~
> Relax access modifiers for Slf4jLoggingService

- nrich-excel-spring-boot-starter/src/main/java/net/croz/nrich/excel/starter/configuration/NrichExcelAutoConfiguration.java
- nrich-excel/README.md
- nrich-excel/build.gradle
- nrich-excel/src/main/java/net/croz/nrich/excel/converter/DefaultCellValueConverter.java
- nrich-excel/src/test/java/net/croz/nrich/excel/ExcelTestConfiguration.java
- nrich-excel/src/test/java/net/croz/nrich/excel/converter/DefaultCellValueConverterTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorTest.java
- nrich-excel/src/test/java/net/croz/nrich/excel/stub/TestEnum.java
- nrich-excel/src/test/resources/messages.properties
2.1.1
* Module:
nrich-excel
Add support for resolving enum description from message source when writing enums to excel
Add support for resolving enum description from message source when writing enums to excel
> Add support for resolving enum description from message source in excel

- nrich-search-api/src/main/java/net/croz/nrich/search/api/model/SearchConfiguration.java
- nrich-search-api/src/main/java/net/croz/nrich/search/api/model/SearchJoin.java
- nrich-search-api/src/main/java/net/croz/nrich/search/api/model/subquery/SubqueryConfiguration.java
- nrich-search/README.md
- nrich-search/src/main/java/net/croz/nrich/search/support/JpaQueryBuilder.java
- nrich-search/src/main/java/net/croz/nrich/search/util/PathResolvingUtil.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/util/PathResolvingUtilTest.java
- nrich-search/src/test/java/net/croz/nrich/search/util/testutil/PathResolvingUtilGeneratingUtil.java
2.1.1
* Module:
nrich-search, nrich-search-api
Added support for specifying JoinType when adding projections and conditions to query.
Added support for specifying JoinType when adding projections and conditions to query. The JoinType can be specified on SearchConfiguration level and overridden on each join by explicitly specifying `SearchJoin`.
> Add support for specifiying join type for projections and restrictions

- nrich-core-api/src/main/java/net/croz/nrich/core/api/exception/ExceptionWithMessage.java
- nrich-core-api/src/main/java/net/croz/nrich/core/api/exception/ExceptionWithMessageCode.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/service/BaseNotificationResponseService.java
- nrich-notification-api/src/main/java/net/croz/nrich/notification/api/service/NotificationResolverService.java
- nrich-notification/README.md
- nrich-notification/build.gradle
- nrich-notification/src/main/java/net/croz/nrich/notification/service/DefaultNotificationResolverService.java
- nrich-notification/src/main/java/net/croz/nrich/notification/service/WebMvcNotificationResponseService.java
- nrich-notification/src/test/java/net/croz/nrich/notification/service/DefaultNotificationResolverServiceTest.java
- nrich-notification/src/test/java/net/croz/nrich/notification/stub/NotificationResolverServiceTestExceptionWithMessage.java
- nrich-notification/src/test/java/net/croz/nrich/notification/stub/NotificationResolverServiceTestExceptionWithMessageCode.java
- nrich-notification/src/test/resources/messages.properties
- nrich-webmvc/build.gradle
- nrich-webmvc/src/main/java/net/croz/nrich/webmvc/advice/NotificationErrorHandlingRestControllerAdvice.java
2.1.1
* Module:
nrich-notification, nrich-webmvc
Add support for resolving of notification content from message or message code for exceptions
Add support for resolving of notification content from message or message code for exceptions, move handling of exception arguments to NotificationResolver service
> Support resolving of notification content from exception message or message code

- nrich-registry/src/main/java/net/croz/nrich/registry/data/service/DefaultRegistryDataService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/data/util/HibernateUtil.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/controller/RegistryDataControllerTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/util/HibernateUtilTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/util/stub/HibernateUtilTestEntity.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/util/testutil/HibernateUtilGeneratingUtil.java
2.1.1
* Module:
nrich-registry
Add entity initialization when returning a value from create or update method in DefaultRegistryDataService to avoid lazy init exception.
> Avoid lazy init exception in DefaultRegistryDataService 

- nrich-validation-spring-boot-starter/src/main/java/net/croz/nrich/validation/starter/configuration/NrichValidationAutoConfiguration.java
- nrich-validation-spring-boot-starter/src/test/java/net/croz/nrich/validation/starter/configuration/NrichValidationAutoConfigurationTest.java
2.1.1
* Module:
nrich-validation-spring-boot-starter
Add support for programmatically registered constraints on hibernate entites by registering Spring's validator with Hibernate BeanValidationEventListener.
Add support for programmatically registered constraints on hibernate entites by registering Spring's validator with Hibernate BeanValidationEventListener.
-  ~~I have added tests to cover my changes~~
> Support  programmatically registered constraints on Hibernate entities

- nrich-core-api/src/main/java/net/croz/nrich/core/api/exception/DefaultExceptionWithArguments.java
nrich-core-api
* Module:
nrich-core-api
Add DefaultExceptionWithArguments class for easier usage of ExceptionWithArguments interface
Add DefaultExceptionWithArguments class for easier usage of ExceptionWithArguments interface
> Introduce DefaultExceptionWithArguments

- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/service/DefaultRegistryDataServiceTest.java
- nrich-registry/src/test/java/net/croz/nrich/registry/data/testutil/RegistryDataGeneratingUtil.java
- nrich-search/src/main/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverter.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/DefaultStringToEntityPropertyMapConverterTest.java
- nrich-search/src/test/java/net/croz/nrich/search/converter/stub/DefaultStringToEntityPropertyMapConverterTestEntity.java
2.4.1
* Module:
nrich-search, nrich-registry
Fallback to searching by association id when association name has been sent as property name
Fallback to searching by association id when association name has been sent as property name
> Fallback to search by association id when association name has been sent as property name

- .github/workflows/publish.yml
- build.gradle
- gradle.properties
* nrich version: 2.4.1
Switch to a user token in the publish plugin authentication configuration.
This is needed because of changes in Maven Central authentication.
Using Nexus UI username and password login in the publish plugin configuration is no longer supported.
> Switch to a user token in the publish plugin authentication configuration

- nrich-registry/src/main/java/net/croz/nrich/registry/core/constants/RegistryQueryConstants.java
- nrich-registry/src/main/java/net/croz/nrich/registry/core/service/EntityManagerRegistryEntityFinderService.java
2.5.1
* Module:
nrich-registry
Removed join fetches from the entity find query since it causes issues with multiple associations and is unnecessary for the query.
Removed join fetches from the entity find query since it causes issues with multiple associations and is unnecessary for the query.
> Remove join fetches from entity find query

- nrich-search/src/main/java/net/croz/nrich/search/support/JpaQueryBuilder.java
- nrich-search/src/main/java/org/springframework/data/jpa/repository/query/NrichQueryUtils.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/JpaSearchRepositoryExecutorGeneratingUtil.java
2.5.4
* Module:
nrich-search
Add support for sorting by subclass properties when going through Spring (Hibernate already supports it but Spring fails with exception)
Add support for sorting by subclass properties when going through Spring (Hibernate already supports it but Spring fails with exception)
> Add support for sorting by subclass properties

- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationService.java
- nrich-registry/src/test/java/net/croz/nrich/registry/RegistryTestConfiguration.java
- nrich-registry/src/test/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationServiceTest.java
2.5.2
* Module:
nrich-registry
Add support for sorting properties of embedded id
Add support for sorting properties of embedded id
> Add support for sorting properties of embedded id

- nrich-registry-api/src/main/java/net/croz/nrich/registry/api/core/model/RegistryOverrideConfiguration.java
- nrich-registry/src/main/java/net/croz/nrich/registry/configuration/service/DefaultRegistryConfigurationService.java
- nrich-registry/src/main/java/net/croz/nrich/registry/security/interceptor/RegistryConfigurationUpdateInterceptor.java
- nrich-registry/src/test/java/net/croz/nrich/registry/RegistryTestConfiguration.java
- nrich-registry/src/test/java/net/croz/nrich/registry/core/testutil/RegistryConfigurationGeneratingUtil.java
2.5.2
* Module:
nrich-registry
Add default values to registry override so user doesn't have to specify all the values when overriding configuration
Add default values to registry override so user doesn't have to specify all the values when overriding configuration
> Add default values to registry override

- nrich-excel/src/main/java/net/croz/nrich/excel/generator/PoiExcelReportGenerator.java
- nrich-excel/src/test/java/net/croz/nrich/excel/generator/PoiExcelReportGeneratorTest.java
…ula characters
2.5.3
* Module:
nrich-excel
Limit quoting strings in excel to string that starts with one of formula characters
Limit quoting strings in excel to string that starts with one of formula characters
- ~~My change requires a change to the documentation~`
> Limit quoting strings in excel to formulas

- nrich-search/src/main/java/net/croz/nrich/search/parser/SearchDataParser.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/testutil/JpaSearchRepositoryExecutorGeneratingUtil.java
2.6.0
* Module:
nrich-search
Fix issue with collection attributes not being recognized and using a join instead of exist query by default
Fix issue with collection attributes not being recognized and using a join instead of exist query by default
> Fix issue with collection attributes not being recognized

- nrich-webmvc/src/main/java/net/croz/nrich/webmvc/service/DefaultTransientPropertyResolverService.java
- nrich-webmvc/src/test/java/net/croz/nrich/webmvc/service/DefaultTransientPropertyResolverServiceTest.java
* nrich version: 2.7.0
* Module: nrich-webmvc
Existing code caused NPE when type did not extend Object class. 
This is the case with interfaces, such as java.util.Map.
Existing code caused NPE when type did not extend Object class. 
This is the case with interfaces, such as java.util.Map.
> Avoid NPE in DefaultTransientPropertyResolverService

- nrich-search-api/src/main/java/net/croz/nrich/search/api/model/operator/DefaultSearchOperator.java
- nrich-search/src/test/java/net/croz/nrich/search/repository/support/JpaQueryBuilderTest.java
2.8.1
* Module:
nrich-search, nrich-search-api
Add lower in operator to enable searching by lower collection values
Add lower in operator to enable searching by lower collection values
> Add lower in operator to enable searching by lower collection values
